/*
 * This file is generated by jOOQ.
 */
package com.thee5176.record.springboot_cqrs_query.Domain.model.enums;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum Element {

    Assets("Assets"),

    Liabilities("Liabilities"),

    Equity("Equity"),

    Revenue("Revenue"),

    Expenses("Expenses"),

    Other("Other");

    private final String literal;

    private Element(String literal) {
        this.literal = literal;
    }
}
