name: Build and Run with Docker Compose

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build:
    name: Build and Run with Docker Compose
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Clean up Docker environment
        run: docker compose down -v --remove-orphans
          
      - name: Run Flyway migrations
        run: mvn flyway:migrate

      - name: Build application package
        run: mvn clean package

      - name: Build and run all services with Docker Compose
        run: docker compose up -d --build